# Generated by Django 4.0.6 on 2022-07-18 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_rename_body_entry_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='lst',
            field=models.ForeignKey(db_column='list', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='lists.list'),
        ),
    ]
