# Generated by Django 4.0.6 on 2022-07-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_alter_entry_lst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
